---
# handlers file for beats

- name: restart beat
  service: name={{ beat }} state=restarted enabled=yes
  when: os_type == 'unix' and start_service and restart_on_change and not beats_started.changed and beat_install.changed
  
- name: restart beat
  win_service:
    name: "{{ beat }}"
    state: restarted
  when: os_type == 'win' and start_service and restart_on_change and not beats_started.changed and beat_install.changed